### ISSUE TITLE
Malicious docker container [BUG]

### ISSUE THREAD

**Issue by omega1582** [RunOnFlux/flux#1090]
Docker image is running traffMonetizer.  As far as i've been aware, these type of apps(mining, bandwith mining...etc) are not allowed on Flux Network. Docker Hub Repo is holdroot/tft.  https://hub.docker.com/r/holdroot/tft.   
See atttache image.  

![traffMonetizer](https://github.com/RunOnFlux/flux/assets/63751693/5ccc2e51-b0d0-4293-8e03-89fb6566f5fc)

**Comment by TheTrunk** [comment]
Thank you for the report. Our tests have shown the same.

Image is now blocked and nodes will start to remove the application.

**Comment by 0xJohnny21** [comment]
The same user now running a hidden proxy server along with the html5 game.
Suspicious...
