### ISSUE TITLE
Traffmonetizer container running [BUG]

### ISSUE THREAD

**Issue by omega1582** [RunOnFlux/flux#1097]
Docker image is running traffMonetizer. As far as i've been aware, these type of apps(mining, bandwith mining...etc) are not allowed on Flux Network. Docker Hub Repo is jackxhxm/redis. https://hub.docker.com/r/jackxhxm/redis.
See atttached image.
![traffMonetizer](https://github.com/RunOnFlux/flux/assets/63751693/bb78789e-0d7a-4ac1-8dd5-ec7c30460ec7)

**Comment by TheTrunk** [comment]
Thank you very much for the report. We are testing and will be blocking that image asap.
