### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Etimad1401** [RunOnFlux/flux#393]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - OS: [e.g. Ubuntu 18.04 LTS]
 - Version [e.g. v0.65.0]
 - Daemon [e.g. v4.1.0]
 - Benchmark [ e.g. v1.4.1]

**Additional context**

**Comment by TheTrunk** [comment]
@Etimad1401 I believe accidental opening as no issue reported.
