### ISSUE TITLE
Extra steps needed for configuring grandfathered nodes, i.e, Presearch

### ISSUE THREAD

**Issue by manolinux** [RunOnFlux/flux#409]
**Is your feature request related to a problem? Please describe.**

There are nodes in Presearch that need an extra step of configuration: grandfathered nodes, only with the registration code is not enough, cause you need to upload pub & private keys in order to keep them grandfathered (special status that requires only 1000 PRE to stake instead of 2000).

That extra step can only be achieved by SSHing the nodes or being able to upload the keys prior to running, thing that I've been told it's not possible to do in Flux.

**Describe the solution you'd like**
Extra steps for further configuring after setting up, like uploading files, like in the app marketplace having extra fields for uploading configuration files, apart from environment variables setting.

**Comment by jah037** [comment]
How to reconnect the node

**Comment by jah037** [comment]
![E732E922-323B-4818-9C5E-0DC1BCA5D830](https://user-images.githubusercontent.com/82873359/209736947-92688070-272a-4954-b7d3-6dae9fb4afdb.png)
![DC53D3BD-0554-481E-938E-702BDC6354FC](https://user-images.githubusercontent.com/82873359/209736949-5cff6dd6-76ac-43a8-a2ed-4dee71f77b1c.png)

**Comment by jah037** [comment]
How to reconnect it
