### ISSUE TITLE
[BUG] Massive load on Docker Hub

### ISSUE THREAD

**Issue by binman-docker** [RunOnFlux/flux#510]
**Describe the bug**

This repository makes multiple calls to Docker Hub every time it runs. Given the distributed nature of the network, this is causing serious load on Docker Hub and degrading the experience for other users.

This is the code that calls Hub: https://github.com/RunOnFlux/flux/blob/9d48d9526a01b847e84a6cbdabad12c511b30657/ZelBack/src/services/appsService.js#L2897

Here is where it is referenced:
https://github.com/RunOnFlux/flux/search?q=verifyRepository
https://github.com/RunOnFlux/flux/search?q=checkDockerAccessibility

**To Reproduce**

Run Flux

**Expected behavior**

Flux should be a good citizen and limit calls to outside resources. 

**Screenshots**

Repos API request volume on Docker Hub since this project launched:
![image](https://user-images.githubusercontent.com/17711346/159377822-604a16af-7b4a-479d-b4ae-d0a8d21ead84.png)

**Environment(please complete the following information):**

Any

**Additional context**

I don't know exactly what the code is attempting to do, but we'd like to work with you to do it better without harming Docker Hub's other users. I'm sure some of these calls are unnecessary - you could probably just run the image and see if it works or not (the image pull will fail if it doesn't exist), rather than making multiple calls to the API first.

**Comment by binman-docker** [comment]
I should mention we traced this back to Flux based on the API requests matching the repos in this list: https://raw.githubusercontent.com/runonflux/flux/master/helpers/repositories.json

**Comment by TheTrunk** [comment]
Thank you for reaching out as we were unaware of this and underestimated the load.

The upsurge in requests is caused by our halving fork and it is further expected to rise up to a 2x amount of requests. New nodes are joining the network and by doing so they are verifying all application messages specifications which is doing a call to docker hub.

We will work on adjusting this check asap (also to other external 3rd parties)

**Comment by binman-docker** [comment]
Appreciate it, thank you! So far it's looking a lot better, we'll keep an eye on it.

**Comment by TheTrunk** [comment]
Thank you for the update, please keep us posted and if you have some nice graph that would be great to see too :)
I believe about 90% of node operators have already updated to the release v3.12.0, rest should be updating in the upcoming days which shall ease the load even more.
