### ISSUE TITLE
Add Copyright notice and License

### ISSUE THREAD

**Issue by w2vy** [RunOnFlux/flux#559]
The source files do no have any Copyright messages, should they be added?
No LICENSE file either, I assume MIT like Fluxd?

**Comment by TheTrunk** [comment]
Flux actually has [AGPL-3.0 license](https://github.com/RunOnFlux/flux/blob/master/LICENSE)
I think copyright in every file is not needed, might be good to be included in README or in COPYING file but the license kind of states all,
