### ISSUE TITLE
Restarting PC while Node is running.

### ISSUE THREAD

**Issue by Noel2077** [RunOnFlux/flux#610]
Hello. Im gonna run a Cumulus Node on my Mining PC with win10 on it. When my PC auto-restarts do i have to manually turn on the Node again or is it self restarting?

**Comment by Adminsupportt** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by TheTrunk** [comment]
It is not possible to host a node on windows machine.
