### ISSUE TITLE
[BUG] Can't launch Presearch node - imageTags.forEach is not a function

### ISSUE THREAD

**Issue by biklas7** [RunOnFlux/flux#624]
**Describe the bug**
I'm trying to launch a Presearch node from the marketplace app.

**To Reproduce**
1. Go to https://home.runonflux.io/apps/marketplace
2. Click on PresearchNode
3. Enter the registration code and press Start Launching Marketplace App
5. See error imageTags.forEach is not a function

**Expected behavior**
Should continue the launching process.

**Screenshots**
![image](https://user-images.githubusercontent.com/4192633/174133781-a1f804e5-9dd4-4f0b-ae05-66f6d34174e6.png)

**Environment(please complete the following information):**
 - OS: Windows 11
 - Browser chrome, firefox, safari
 - Version FluxOS v3.21.1
 - Daemon 6000050

**Comment by Cabecinha84** [comment]
Thank you for your report. The bug should be fixed.
