### ISSUE TITLE
[BUG] can't boot flux node in NAT network?

### ISSUE THREAD

**Issue by sudowanderer** [RunOnFlux/flux#699]
**Describe the bug**
I am install flux node in my home. My home network is in `NAT`, I get a `NAT` IP address from my `ISP`. I got below error after install:
`location:/zelflux/debug.log`

>  Flux is not available for outside communication

It seems like other peers cannot connect me because the `IP` fluxbench getted was not my real IP, techinically, other peers can not connect me cause am in a `NAT` network.

So I was wondering is any solutions to solve this problem? 

BTW, I can get public `IPv6` address from `ISP`, But it seems that currently flux nodes doesn't support connect each other with IPv6.

**Comment by schererjay** [comment]
What is the expectation on this bug fix?  I'm running 16 cumulus nodes via proxmox on 2 different home networks and this is not an uncommon error throughout the week.  I have my own set up scripts that detect this issue and most of the time the only solution is a reboot of the VM after fluxbench reports toaster.  This error is being reported consistently on discord channels all with similar results and similar log files.  IE, this is reproduced frequently.  Be happy to help with log files if needed.

**Comment by WyattLiu** [comment]
I saw massive cumulus nodes down this week. I think they made a mistake in a recent update thinking NIC IP is the "IP"
