### ISSUE TITLE
🚨 ERROR: OS version not supported

### ISSUE THREAD

**Issue by gonzo4233** [RunOnFlux/flux#761]
**Describe the bug**
every time i type in the "bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)"
I get this message 🚨 ERROR: OS version not supported, I have tried every version of Ubuntu and still no luck, I've been trying to install a flux node for 3 weeks now

option 1 will not install 

**Additional context**

**Comment by TheTrunk** [comment]
This is not an issue of Flux but related to Flux multitool scripts. Please open an issue there
https://github.com/RunOnFlux/fluxnode-multitool
