### ISSUE TITLE
[BUG] No Nodes Assigned Using Jet Pack 2

### ISSUE THREAD

**Issue by FliKites** [RunOnFlux/flux#778]
**Describe the bug**

Attempted 2 different deployments from Jet Pack 2 in which both failed to deploy any nodes.

**Expected behavior**

I expected nodes to be deployed and the ability to see the "specifications" for the app load both in "global" and "local"

**Screenshots**

App 1 https://prnt.sc/Tb0PCqanC1J9

App 2 https://prnt.sc/lLdBXxoY3bub

**Environment:**

 - OS: Windows 10 Pro 64Bit
 - Browser: Brave
 - Browser Version: v1.45.116
 - Jet Pack 2 Beta Version:  v0.221027.0531

**Additional context**

I updated to the latest wallet before using Jet Pack 2

**Comment by TheTrunk** [comment]
Jetpack seems to be assigning 'acALL' to geolocation field instead of ommiting it.
I have allowed acALL to be a valid geolocation and will be present in the next flux version. Once nodes update to it, app will spawn well
f7175576bfb1a8ad5cff9b0a33cde81b5b9d635f #779

**Comment by FliKites** [comment]
Awesome! Thank You!

**Comment by TheTrunk** [comment]
Seems to be resolved with the latest flux release.
Let us know how the VPNs behave :)
