### ISSUE TITLE
[FEAT] GEOTARGETING EXCLUSIONS AT CONTINENT LEVEL

### ISSUE THREAD

**Issue by FliKites** [RunOnFlux/flux#865]
Currently their is no way to exclude "ALL" regions/countries for a specific continent. 

You can see the behavior when trying to do so via the screenshots below:

![On JetPack](https://user-images.githubusercontent.com/72367027/206831891-1c040b11-0599-4b49-bcab-b4dfcbbcf65c.png)
![On FluxOS](https://user-images.githubusercontent.com/72367027/206831895-48bbeb0a-7b5e-48ce-8b51-829547b566b3.png)

I am requesting that an option to exclude "ALL" countries and regions within a selected continent, be added.  

This specific configuration in the screenshot attempts to disable the 5 big surveillance countries, which was not possible.

**Comment by TheTrunk** [comment]
Hi,
On Flux backend and combination shall be possible however UI of home.runonflux.io nor Jetpack may not be coded for that. 
So the goal is to exclude all of europe, then that would be 'a!cEU' flag and app will not be spawned in any country of europe.
On home.runonflux.io UI it shall be then selected exactly like this:
<img width="1342" alt="Screenshot 2022-12-10 at 13 11 06" src="https://user-images.githubusercontent.com/29507418/206835073-4cf491de-b864-4f2a-a4f4-a487169981c1.png">

Can you please expand on the question as I may have misuderstood.

**Comment by FliKites** [comment]
The screenshot you showed me is the same configuration I used.It created a "null" entry when I did that. The goal is to exclude all countries within a continent, from the GUI.  ---- On Sat, 10 Dec 2022 01:13:07 -0500  ***@***.***  wrote ----
Hi,
On Flux backend and combination shall be possible however UI of home.runonflux.io nor Jetpack may not be coded for that.
So the goal is to exclude all of europe, then that would be 'a!cEU' flag and app will not be spawned in any country of europe.
On home.runonflux.io UI it shall be then selected exactly like this:

Can you please expand on the question as I may have misunderstood.

**Comment by FliKites** [comment]
I apologize. I need to correct myself. The goal is to ban one country within a continent, without having to select a specific region in that country. But to ban all regions within a country. ---- On Sat, 10 Dec 2022 01:34:04 -0500  ***@***.***  wrote ----The screenshot you showed me is the same configuration I used.It created a "null" entry when I did that. The goal is to exclude all countries within a continent, from the GUI.  ---- On Sat, 10 Dec 2022 01:13:07 -0500  ***@***.***  wrote ----
Hi,
On Flux backend and combination shall be possible however UI of home.runonflux.io nor Jetpack may not be coded for that.
So the goal is to exclude all of europe, then that would be 'a!cEU' flag and app will not be spawned in any country of europe.
On home.runonflux.io UI it shall be then selected exactly like this:

Can you please expand on the question as I may have misunderstood.

**Comment by FliKites** [comment]
Did I need to select "NONE" ? ---- On Sat, 10 Dec 2022 01:34:04 -0500  ***@***.***  wrote ----The screenshot you showed me is the same configuration I used.It created a "null" entry when I did that. The goal is to exclude all countries within a continent, from the GUI.  ---- On Sat, 10 Dec 2022 01:13:07 -0500  ***@***.***  wrote ----
Hi,
On Flux backend and combination shall be possible however UI of home.runonflux.io nor Jetpack may not be coded for that.
So the goal is to exclude all of europe, then that would be 'a!cEU' flag and app will not be spawned in any country of europe.
On home.runonflux.io UI it shall be then selected exactly like this:

Can you please expand on the question as I may have misunderstood.

**Comment by TheTrunk** [comment]
Hi, if you wish to ban all the countries within the continent then the above screenshot of mine is correct. Or you can select the NONE (which basically means ban ALL - we will correct it to be ALL instead of NONE)

**Comment by FliKites** [comment]
Thanks for clarification. Noted.  ---- On Sat, 10 Dec 2022 10:44:39 -0500  ***@***.***  wrote ----
Hi, if you wish to ban all the countries within the continent then the above screenshot of mine is correct. Or you can select the NONE (which basically means ban ALL - we will correct it to be ALL instead of NONE)
