### ISSUE TITLE
Malicious image

### ISSUE THREAD

**Issue by 0xJohnny21** [RunOnFlux/flux#886]
@TheTrunk  Hello, i see some weird files on this docker image.(fabreeze/flux-proxy-test) I see some bandwidth mining app is running on.. 
As far i know these are not allowed on flux network
I have attached a screenshot of the directory in container
https://traffmonetizer.com/
![image](https://user-images.githubusercontent.com/121117160/210056336-2059eaee-19c9-4d04-bba6-121ac5ac38b2.png)

_Originally posted by @0xJohnny21 in https://github.com/RunOnFlux/flux/issues/836#issuecomment-1368039732_

**Comment by TheTrunk** [comment]
Hi,
Thank you for the report.
All sorts of mining applications including bandwidth mining are prohibited on Flux network.
In the upcoming version of 3.31.0 we are introducing more robust blacklist features that will take carw of this in a more automated way 👍

**Comment by 0xJohnny21** [comment]
ok, now version 3.31.0 is implemented, any update?

**Comment by TheTrunk** [comment]
Blacklisted.

**Comment by fluxboi36** [comment]
If this app is going to be blacklisted, then so should the following app:
monestry24/go-server

fabreeze/flux-proxy-test is literally a clone of it.

**Comment by TheTrunk** [comment]
Blacklisted. We got several more reports.

**Comment by qwiklabstutorials** [comment]
> Blacklisted. We got several more reports.

Would you please check the image before backlisting? there is nothing wrong in image monestry24/go-server

**Comment by fluxboi36** [comment]
I have a lot of copies of the monestry24/go-server app and I'm happy to provide more proof that it behaved exactly like fabreeze/flux-proxy-test.

If you claim there is currently nothing wrong with it, it's simply because the app has been updated to pull its config files from an external server.
