### ISSUE TITLE
Flux/Info API addition - Node Rank

### ISSUE THREAD

**Issue by 2ndtlmining** [RunOnFlux/flux#916]
**Is your feature request related to a problem? Please describe.**

Currently the Node information API : **http://<ip>:<port./flux/info** contains a lot of great information around the node, benchmarks, maintenance and even the application running on it. Would it be possible to add the Rank into the API?

**Describe the solution you'd like**
Node rank included in the API

**Describe alternatives you've considered**

Currently making use of the API: https://explorer.runonflux.io/api/status?q=getFluxNodes
This provides a complete list of all 15000 nodes and then perform filtering to find the rank.

Hope to improve performance by reducing the API calls as most of the node information is already available in the Info api

**Comment by TheTrunk** [comment]
Currently flux daemon does not provide it on the calls flux/info call is using. Adding the rank there would affect the performance of the call significantly. 
@blondfrogs Can we add 'rank' to getzelnodestatus call on daemon?

**Comment by 2ndtlmining** [comment]
Cheers
