### ISSUE TITLE
Fractus Count  - getzelnodecount API

### ISSUE THREAD

**Issue by 2ndtlmining** [RunOnFlux/flux#917]
**Is your feature request related to a problem? Please describe.**

Hey team wanted to know if it will be possible to add Fractus counts into the existing API:

**https://api.runonflux.io/daemon/getzelnodecount** 

Please

**Describe the solution you'd like**

Could we just add the count of Fractus similar to what we have today:
![image](https://user-images.githubusercontent.com/108513481/214236136-a8942501-29e1-4fc2-aff4-adac73c4e4fe.png)

**thunder-enabled: XXXX**

**Describe alternatives you've considered**

Unfortunately havent found alternative

**Additional context**
Like to include the counts to the Fluxnode app

**Comment by TheTrunk** [comment]
From Flux blockchain - Flux Daemon prespecitve, Thunder node class has the same collateral requirements and behaves the same as Cumulus node. The difference is in the benchmarking perspective and how FluxOS later treats that. Currently it is not technically doable to put thunder-enabled property there in some easy way - would require a change in fluxbench/fluxd.
@blondfrogs That would probably mess with serialisation on how flux confirmation messages as sent to network if we add like thunder boolean property right.

**Comment by 2ndtlmining** [comment]
@TheTrunk Totally understand and make sense. Daemon works with the reward/rank side. This is not high priority at all, just wanted to know if there is an easy way to get some sort of count. I potentially pull all Zellnodes and then filter Thunder = True just wanted to see if there is possibly something else that i can hit to get a count.

**Comment by sygem** [comment]
I fetch this data: https://stats.runonflux.io/fluxinfo?projection=benchmark then look for the thunder flag on each node. It's the only way I know for now, because it's only the benchmark that knows about Fractus nodes.

**Comment by 2ndtlmining** [comment]
@sygem Thanks had a quick look

![image](https://user-images.githubusercontent.com/108513481/214625867-1b48be4e-823c-4958-8462-44b291f01cb9.png)

Data is good, just need to figure out how to make it quick as it will be a big pull :)

**Comment by sygem** [comment]
The projection is quite flexible - you can just choose the fields you want to minimize data. Like this: https://stats.runonflux.io/fluxinfo?projection=benchmark.bench.thunder,benchmark.bench.ipaddress

**Comment by JKTUNING** [comment]
I had a question about this in general, how often is this data updated/scraped?

**Comment by 2ndtlmining** [comment]
> https://stats.runonflux.io/fluxinfo?projection=benchmark.bench.thunder,benchmark.bench.ipaddress

Super thanks, didnt you you could filter the output. Reduces the size drastically and cutting time almost half. Ill have a dabble to see how i can make it work. Thanks for the help!

![image](https://user-images.githubusercontent.com/108513481/214646011-b8aa9a9a-a906-4bb1-bd5b-bc2037d03f96.png)

**Comment by 2ndtlmining** [comment]
Managed to get data making use of the stat.runonflux.io data. Successfully updated the Fluxnode website to include this data.

![image](https://user-images.githubusercontent.com/108513481/215630244-d9e706d5-498b-421d-9ee5-e68ba3173265.png)

thanks @sygem
