### ISSUE TITLE
[BUG] Logs Don't Populate

### ISSUE THREAD

**Issue by flikites** [RunOnFlux/flux#964]
**Describe the bug**
From time to time (for multiple people/users) the logs do not populate 

Right now for the app named `dane` their is only 1 node that can show logs out of 4 nodes. 

Node Showing Logs: 76.154.1.138

Nodes Not Showing Logs: 
73.153.181.163	
73.78.222.180
24.8.167.214

**To Reproduce**
Intermittent, happens randomly on some nodes, and others not. 

See screenshot for specific node/version

Other members of the community are also experiencing the same behavior.

**Expected behavior**
The logs should ALWAYS generate for an app, every time the "logs" tab is clicked, I should not have to restart the container or do something to get them to work.

**Screenshots**
https://prnt.sc/iLZNE_UOGTDN - FluxOS v3.35.0 
https://prnt.sc/oR09C6Esjaih - FluxOS v3.36.3
https://prnt.sc/yGrL0MPvPJxf - FluxOS v3.36.3

**Environment(please complete the following information):**
 - OS: [e.g. Linux Mint 21.1]
 - Browser [ Brave v1.48.171 (Feb 23, 2023) ]
 - Version [ FluxOS v3.35.0 & FluxOS v3.36.3 ]

**Additional context**
Happens often, super annoying.

**Comment by XK4MiLX** [comment]
Fixed.
